<?php

namespace ContainerZRKn89f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6ewV9MSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6ewV9MS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6ewV9MS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manager' => ['privates', '.errored..service_locator.6ewV9MS.Doctrine\\Persistence\\ObjectManager', NULL, 'Cannot autowire service ".service_locator.6ewV9MS": it references interface "Doctrine\\Persistence\\ObjectManager" but no such service exists. You should maybe alias this interface to the existing "doctrine.orm.default_entity_manager" service.'],
            'panierRepository' => ['privates', 'App\\Repository\\PanierRepository', 'getPanierRepositoryService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'manager' => 'Doctrine\\Persistence\\ObjectManager',
            'panierRepository' => 'App\\Repository\\PanierRepository',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
