<?php

namespace ContainerR4BaTaq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B5KWP_BService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b5KWP.b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b5KWP.b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'etatRepository' => ['privates', 'App\\Repository\\EtatRepository', 'getEtatRepositoryService', true],
            'manager' => ['privates', '.errored..service_locator.b5KWP.b.Doctrine\\Persistence\\ObjectManager', NULL, 'Cannot autowire service ".service_locator.b5KWP.b": it references interface "Doctrine\\Persistence\\ObjectManager" but no such service exists. You should maybe alias this interface to the existing "doctrine.orm.default_entity_manager" service.'],
            'panierRepository' => ['privates', 'App\\Repository\\PanierRepository', 'getPanierRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'commandeRepository' => 'App\\Repository\\CommandeRepository',
            'etatRepository' => 'App\\Repository\\EtatRepository',
            'manager' => 'Doctrine\\Persistence\\ObjectManager',
            'panierRepository' => 'App\\Repository\\PanierRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
