<?php

namespace ContainerK1udMo7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GW9vPSRService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GW9vPSR' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GW9vPSR'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CommandeController::index' => ['privates', '.service_locator.5Bc9YuW', 'get_ServiceLocator_5Bc9YuWService', true],
            'App\\Controller\\CommandeController::indexForUser' => ['privates', '.service_locator.5Bc9YuW', 'get_ServiceLocator_5Bc9YuWService', true],
            'App\\Controller\\CommandeController::valideCommande' => ['privates', '.service_locator.sP0eG_2', 'get_ServiceLocator_SP0eG2Service', true],
            'App\\Controller\\LigneCommandeController::add' => ['privates', '.service_locator.CmHNcky', 'get_ServiceLocator_CmHNckyService', true],
            'App\\Controller\\PanierController::addOnPanier' => ['privates', '.service_locator.vM0xZZb', 'get_ServiceLocator_VM0xZZbService', true],
            'App\\Controller\\PanierController::deleteAllOnPanier' => ['privates', '.service_locator.n3dpdY9', 'get_ServiceLocator_N3dpdY9Service', true],
            'App\\Controller\\PanierController::deleteOnPanier' => ['privates', '.service_locator.BHo36d5', 'get_ServiceLocator_BHo36d5Service', true],
            'App\\Controller\\PanierController::index' => ['privates', '.service_locator.n3dpdY9', 'get_ServiceLocator_N3dpdY9Service', true],
            'App\\Controller\\ProduitController::addProduit' => ['privates', '.service_locator.1cFtlgg', 'get_ServiceLocator_1cFtlggService', true],
            'App\\Controller\\ProduitController::delete' => ['privates', '.service_locator.VP68NKc', 'get_ServiceLocator_VP68NKcService', true],
            'App\\Controller\\ProduitController::edit' => ['privates', '.service_locator.1cFtlgg', 'get_ServiceLocator_1cFtlggService', true],
            'App\\Controller\\ProduitController::index' => ['privates', '.service_locator.BHo36d5', 'get_ServiceLocator_BHo36d5Service', true],
            'App\\Controller\\SecurityController::inscription' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\admin\\AdminController::stat' => ['privates', '.service_locator.VP68NKc', 'get_ServiceLocator_VP68NKcService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\CommandeController:index' => ['privates', '.service_locator.5Bc9YuW', 'get_ServiceLocator_5Bc9YuWService', true],
            'App\\Controller\\CommandeController:indexForUser' => ['privates', '.service_locator.5Bc9YuW', 'get_ServiceLocator_5Bc9YuWService', true],
            'App\\Controller\\CommandeController:valideCommande' => ['privates', '.service_locator.sP0eG_2', 'get_ServiceLocator_SP0eG2Service', true],
            'App\\Controller\\LigneCommandeController:add' => ['privates', '.service_locator.CmHNcky', 'get_ServiceLocator_CmHNckyService', true],
            'App\\Controller\\PanierController:addOnPanier' => ['privates', '.service_locator.vM0xZZb', 'get_ServiceLocator_VM0xZZbService', true],
            'App\\Controller\\PanierController:deleteAllOnPanier' => ['privates', '.service_locator.n3dpdY9', 'get_ServiceLocator_N3dpdY9Service', true],
            'App\\Controller\\PanierController:deleteOnPanier' => ['privates', '.service_locator.BHo36d5', 'get_ServiceLocator_BHo36d5Service', true],
            'App\\Controller\\PanierController:index' => ['privates', '.service_locator.n3dpdY9', 'get_ServiceLocator_N3dpdY9Service', true],
            'App\\Controller\\ProduitController:addProduit' => ['privates', '.service_locator.1cFtlgg', 'get_ServiceLocator_1cFtlggService', true],
            'App\\Controller\\ProduitController:delete' => ['privates', '.service_locator.VP68NKc', 'get_ServiceLocator_VP68NKcService', true],
            'App\\Controller\\ProduitController:edit' => ['privates', '.service_locator.1cFtlgg', 'get_ServiceLocator_1cFtlggService', true],
            'App\\Controller\\ProduitController:index' => ['privates', '.service_locator.BHo36d5', 'get_ServiceLocator_BHo36d5Service', true],
            'App\\Controller\\SecurityController:inscription' => ['privates', '.service_locator.j5_bHjD', 'get_ServiceLocator_J5BHjDService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Controller\\admin\\AdminController:stat' => ['privates', '.service_locator.VP68NKc', 'get_ServiceLocator_VP68NKcService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\CommandeController::index' => '?',
            'App\\Controller\\CommandeController::indexForUser' => '?',
            'App\\Controller\\CommandeController::valideCommande' => '?',
            'App\\Controller\\LigneCommandeController::add' => '?',
            'App\\Controller\\PanierController::addOnPanier' => '?',
            'App\\Controller\\PanierController::deleteAllOnPanier' => '?',
            'App\\Controller\\PanierController::deleteOnPanier' => '?',
            'App\\Controller\\PanierController::index' => '?',
            'App\\Controller\\ProduitController::addProduit' => '?',
            'App\\Controller\\ProduitController::delete' => '?',
            'App\\Controller\\ProduitController::edit' => '?',
            'App\\Controller\\ProduitController::index' => '?',
            'App\\Controller\\SecurityController::inscription' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\admin\\AdminController::stat' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CommandeController:index' => '?',
            'App\\Controller\\CommandeController:indexForUser' => '?',
            'App\\Controller\\CommandeController:valideCommande' => '?',
            'App\\Controller\\LigneCommandeController:add' => '?',
            'App\\Controller\\PanierController:addOnPanier' => '?',
            'App\\Controller\\PanierController:deleteAllOnPanier' => '?',
            'App\\Controller\\PanierController:deleteOnPanier' => '?',
            'App\\Controller\\PanierController:index' => '?',
            'App\\Controller\\ProduitController:addProduit' => '?',
            'App\\Controller\\ProduitController:delete' => '?',
            'App\\Controller\\ProduitController:edit' => '?',
            'App\\Controller\\ProduitController:index' => '?',
            'App\\Controller\\SecurityController:inscription' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\admin\\AdminController:stat' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
