<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIOpQtQc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIOpQtQc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIOpQtQc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIOpQtQc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIOpQtQc\App_KernelDevDebugContainer([
    'container.build_hash' => 'IOpQtQc',
    'container.build_id' => '0da68f14',
    'container.build_time' => 1604772110,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIOpQtQc');
