<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX906Abg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX906Abg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX906Abg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX906Abg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX906Abg\App_KernelDevDebugContainer([
    'container.build_hash' => 'X906Abg',
    'container.build_id' => '990b4d2b',
    'container.build_time' => 1606210553,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX906Abg');
