<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxK2b9L\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxK2b9L/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxK2b9L.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxK2b9L\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxK2b9L\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxK2b9L',
    'container.build_id' => '07c2868f',
    'container.build_time' => 1604853426,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxK2b9L');
