<?php

namespace ContainerXSUXwFc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CmHNckyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CmHNcky' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CmHNcky'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'commandeRepository' => ['privates', 'App\\Repository\\CommandeRepository', 'getCommandeRepositoryService', true],
            'etatRepository' => ['privates', 'App\\Repository\\EtatRepository', 'getEtatRepositoryService', true],
            'panierRepository' => ['privates', 'App\\Repository\\PanierRepository', 'getPanierRepositoryService', true],
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'commandeRepository' => 'App\\Repository\\CommandeRepository',
            'etatRepository' => 'App\\Repository\\EtatRepository',
            'panierRepository' => 'App\\Repository\\PanierRepository',
            'produitRepository' => 'App\\Repository\\ProduitRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
